# Women Cloth Reviews Prediction with Multi Nomial Naïve Bayes

## Project Decsription


This project develops a sophisticated text classification system using the Multinomial Naive Bayes algorithm to evaluate and predict ratings based on user-submitted reviews for women’s clothing. Our goal is to harness machine learning to understand consumer sentiment and enhance decision-making processes for both manufacturers and retailers in the fashion industry.

## Library imports

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix, classification_report

## Data source

In [3]:
df = pd.read_csv('https://github.com/YBIFoundation/MachineLearning/raw/main/Dataset/Women%20Clothing%20E-Commerce%20Review.csv')

In [4]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [7]:
df.shape

(23486, 10)

## Data Preprocessing 


In [8]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [11]:
df[df['Review']==""] = np.nan

In [12]:
df['Review'].fillna('No Review', inplace=True)

In [13]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [14]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

## Target variable and Feature variables

In [15]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [36]:
X = df['Review']
y = df['Rating']

In [37]:
X

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

In [38]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

## Test Train split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

In [40]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

## Feature text coversion to Tokens

In [42]:
cv = CountVectorizer(lowercase=True, analyzer='word', ngram_range=(2,3), stop_words='english', max_features=5000)

In [43]:
X_train = cv.fit_transform(X_train)

In [44]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [45]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [46]:
X_test = cv.fit_transform(X_test)

In [47]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'yoga pants', 'zero support',
       'zipper little'], dtype=object)

In [48]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## Model Training

In [50]:
model = MultinomialNB()


In [51]:
model.fit(X_train, y_train)

MultinomialNB()

## Prediciton

In [52]:
y_pred = model.predict(X_test)

In [53]:
y_pred.shape

(7046,)

In [54]:
y_pred

array([5, 3, 5, ..., 1, 4, 5])

## Getting probability of earch predicted class

In [55]:
model.predict_proba(X_test)

array([[0.02625439, 0.01083143, 0.01711761, 0.00819796, 0.9375986 ],
       [0.01730523, 0.01714555, 0.65035479, 0.1004834 , 0.21471103],
       [0.03582725, 0.06660584, 0.12226277, 0.21618005, 0.55912409],
       ...,
       [0.4321192 , 0.34207831, 0.00943121, 0.16642394, 0.04994735],
       [0.45308958, 0.0049263 , 0.00233577, 0.50074437, 0.03890398],
       [0.08430909, 0.04767599, 0.01148417, 0.36485798, 0.49167278]])

## Evaluation of the model

In [57]:
print(confusion_matrix(y_test, y_pred))

[[  30   22   30   43  128]
 [  48   37   49  104  232]
 [  92   84   97  201  387]
 [ 194  138  164  311  716]
 [ 442  389  373  666 2069]]


In [58]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.04      0.12      0.06       253
           2       0.06      0.08      0.06       470
           3       0.14      0.11      0.12       861
           4       0.23      0.20      0.22      1523
           5       0.59      0.53      0.55      3939

    accuracy                           0.36      7046
   macro avg       0.21      0.21      0.20      7046
weighted avg       0.40      0.36      0.38      7046



## Recategores Ratings as Poor(0) and Good(1)

In [59]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

Re-Rating {1,2,3} as 0 and {4,5} as 1

In [60]:
df.replace({'Rating': {
    1:0,
    2:0,
    3:0,
    4:1,
    5:1
}}, inplace=True)

In [62]:
y = df['Rating']
X = df['Review']

## Splitting the data

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)

In [66]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

## Feature text conversion to tokens again

In [67]:
X_train = cv.fit_transform(X_train)
X_test = cv.transform(X_test)

## Model retraining

In [68]:
model.fit(X_train,y_train)

MultinomialNB()

## Predictions

In [69]:
y_pred = model.predict(X_test)

In [70]:
y_pred.shape

(7046,)

In [71]:
y_pred

array([1, 1, 1, ..., 0, 1, 1])

## Re-Evaluation

In [74]:
print(confusion_matrix(y_test, y_pred))

[[ 849  734]
 [ 427 5036]]


In [73]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.54      0.59      1583
           1       0.87      0.92      0.90      5463

    accuracy                           0.84      7046
   macro avg       0.77      0.73      0.75      7046
weighted avg       0.83      0.84      0.83      7046

